source 'https://rubygems.org'

gem 'rake', '~> 12.0'
gem 'rugged', '~> 0.25'
gem "sinatra", "~> 1.4"
gem "thin", "~> 1.7"
gem "json", "~> 2.0"
gem "octokit", "~> 4.6"
gem "mustache", "~> 1.0"
gem "bunny", "~> 2.6"
gem "msgpack", "~> 1.1"
gem "redis", "~> 3.3"
gem "mongo", "~> 2.4"

group :test do
  gem 'minitest', '~> 5.10'
end
